### ISSUE TITLE
我想问下激光雷达应该如何校准呢？

### ISSUE THREAD

**Issue by zbcUN** [Feng1909/fly#1]
激光雷达如何消准？

**Comment by Feng1909** [comment]
目前雷达是用螺丝固连，这个误差很小，如果是用双面胶粘上去的话，使用mid360的imu就可以了

**Comment by zbcUN** [comment]
您好这个项目还在继续吗？我也在用激光雷达定位 用egoplaner做规划，可是egoplaner需要一个速度输入大部分激光雷达里程计并没有给出速度，这里您是怎么解决的呢？

**Comment by Feng1909** [comment]
在继续呢，目前我们有两种解决方案，一种是在定位算法里增加速度输出，另一种方法是将定位信息发送给mavros，mavros会使用IMU自动融合出一个定位信息，这个定位是包含了速度的，输入话题是/mavros/vision_pose/pose，输出话题是/mavros/local_position/pose和/mavros/local_position/odom
